'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ImageServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ImageServiceReference.IImageService")>  _
    Public Interface IImageService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IImageService/GetCustomerImageLarge", ReplyAction:="http://tempuri.org/IImageService/GetCustomerImageLargeResponse")>  _
        Function GetCustomerImageLarge(ByVal customerId As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IImageService/GetCustomerImageSmall", ReplyAction:="http://tempuri.org/IImageService/GetCustomerImageSmallResponse")>  _
        Function GetCustomerImageSmall(ByVal customerId As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IImageService/GetProductImage", ReplyAction:="http://tempuri.org/IImageService/GetProductImageResponse")>  _
        Function GetProductImage(ByVal productId As String) As System.IO.Stream
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IImageServiceChannel
        Inherits ImageServiceReference.IImageService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ImageServiceClient
        Inherits System.ServiceModel.ClientBase(Of ImageServiceReference.IImageService)
        Implements ImageServiceReference.IImageService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetCustomerImageLarge(ByVal customerId As String) As System.IO.Stream Implements ImageServiceReference.IImageService.GetCustomerImageLarge
            Return MyBase.Channel.GetCustomerImageLarge(customerId)
        End Function
        
        Public Function GetCustomerImageSmall(ByVal customerId As String) As System.IO.Stream Implements ImageServiceReference.IImageService.GetCustomerImageSmall
            Return MyBase.Channel.GetCustomerImageSmall(customerId)
        End Function
        
        Public Function GetProductImage(ByVal productId As String) As System.IO.Stream Implements ImageServiceReference.IImageService.GetProductImage
            Return MyBase.Channel.GetProductImage(productId)
        End Function
    End Class
End Namespace
