'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ActionServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RequestBase", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.LoginRequest)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.LogoutRequest)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.CustomerRequest)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.OrderRequest)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.ProductRequest)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.CartRequest)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.TokenRequest))>  _
    Partial Public Class RequestBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AccessTokenField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientTagField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LoadOptionsField() As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RequestIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VersionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AccessToken() As String
            Get
                Return Me.AccessTokenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccessTokenField, value) <> true) Then
                    Me.AccessTokenField = value
                    Me.RaisePropertyChanged("AccessToken")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Action() As String
            Get
                Return Me.ActionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ActionField, value) <> true) Then
                    Me.ActionField = value
                    Me.RaisePropertyChanged("Action")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClientTag() As String
            Get
                Return Me.ClientTagField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientTagField, value) <> true) Then
                    Me.ClientTagField = value
                    Me.RaisePropertyChanged("ClientTag")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LoadOptions() As String()
            Get
                Return Me.LoadOptionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LoadOptionsField, value) <> true) Then
                    Me.LoadOptionsField = value
                    Me.RaisePropertyChanged("LoadOptions")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RequestId() As String
            Get
                Return Me.RequestIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RequestIdField, value) <> true) Then
                    Me.RequestIdField = value
                    Me.RaisePropertyChanged("RequestId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Version() As String
            Get
                Return Me.VersionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VersionField, value) <> true) Then
                    Me.VersionField = value
                    Me.RaisePropertyChanged("Version")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LoginRequest", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LoginRequest
        Inherits ActionServiceReference.RequestBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PasswordField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserNameField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Password() As String
            Get
                Return Me.PasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordField, value) <> true) Then
                    Me.PasswordField = value
                    Me.RaisePropertyChanged("Password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserName() As String
            Get
                Return Me.UserNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserNameField, value) <> true) Then
                    Me.UserNameField = value
                    Me.RaisePropertyChanged("UserName")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LogoutRequest", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LogoutRequest
        Inherits ActionServiceReference.RequestBase
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CustomerRequest", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CustomerRequest
        Inherits ActionServiceReference.RequestBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CriteriaField As ActionServiceReference.CustomerCriteria
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerField As ActionServiceReference.Customer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Criteria() As ActionServiceReference.CustomerCriteria
            Get
                Return Me.CriteriaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CriteriaField, value) <> true) Then
                    Me.CriteriaField = value
                    Me.RaisePropertyChanged("Criteria")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Customer() As ActionServiceReference.Customer
            Get
                Return Me.CustomerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomerField, value) <> true) Then
                    Me.CustomerField = value
                    Me.RaisePropertyChanged("Customer")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OrderRequest", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OrderRequest
        Inherits ActionServiceReference.RequestBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CriteriaField As ActionServiceReference.OrderCriteria
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderIdField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Criteria() As ActionServiceReference.OrderCriteria
            Get
                Return Me.CriteriaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CriteriaField, value) <> true) Then
                    Me.CriteriaField = value
                    Me.RaisePropertyChanged("Criteria")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderId() As Integer
            Get
                Return Me.OrderIdField
            End Get
            Set
                If (Me.OrderIdField.Equals(value) <> true) Then
                    Me.OrderIdField = value
                    Me.RaisePropertyChanged("OrderId")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ProductRequest", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ProductRequest
        Inherits ActionServiceReference.RequestBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CriteriaField As ActionServiceReference.ProductCriteria
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Criteria() As ActionServiceReference.ProductCriteria
            Get
                Return Me.CriteriaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CriteriaField, value) <> true) Then
                    Me.CriteriaField = value
                    Me.RaisePropertyChanged("Criteria")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CartRequest", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CartRequest
        Inherits ActionServiceReference.RequestBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CartItemField As ActionServiceReference.ShoppingCartItem
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ShippingMethodField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CartItem() As ActionServiceReference.ShoppingCartItem
            Get
                Return Me.CartItemField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CartItemField, value) <> true) Then
                    Me.CartItemField = value
                    Me.RaisePropertyChanged("CartItem")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ShippingMethod() As String
            Get
                Return Me.ShippingMethodField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ShippingMethodField, value) <> true) Then
                    Me.ShippingMethodField = value
                    Me.RaisePropertyChanged("ShippingMethod")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TokenRequest", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TokenRequest
        Inherits ActionServiceReference.RequestBase
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CustomerCriteria", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CustomerCriteria
        Inherits ActionServiceReference.Criteria
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IncludeOrderStatisticsField As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomerId() As Integer
            Get
                Return Me.CustomerIdField
            End Get
            Set
                If (Me.CustomerIdField.Equals(value) <> true) Then
                    Me.CustomerIdField = value
                    Me.RaisePropertyChanged("CustomerId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IncludeOrderStatistics() As Boolean
            Get
                Return Me.IncludeOrderStatisticsField
            End Get
            Set
                If (Me.IncludeOrderStatisticsField.Equals(value) <> true) Then
                    Me.IncludeOrderStatisticsField = value
                    Me.RaisePropertyChanged("IncludeOrderStatistics")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Customer", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Customer
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompanyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CountryField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastOrderDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumOrdersField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrdersField() As ActionServiceReference.Order
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VersionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property City() As String
            Get
                Return Me.CityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CityField, value) <> true) Then
                    Me.CityField = value
                    Me.RaisePropertyChanged("City")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Company() As String
            Get
                Return Me.CompanyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompanyField, value) <> true) Then
                    Me.CompanyField = value
                    Me.RaisePropertyChanged("Company")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Country() As String
            Get
                Return Me.CountryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CountryField, value) <> true) Then
                    Me.CountryField = value
                    Me.RaisePropertyChanged("Country")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomerId() As Integer
            Get
                Return Me.CustomerIdField
            End Get
            Set
                If (Me.CustomerIdField.Equals(value) <> true) Then
                    Me.CustomerIdField = value
                    Me.RaisePropertyChanged("CustomerId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastOrderDate() As Date
            Get
                Return Me.LastOrderDateField
            End Get
            Set
                If (Me.LastOrderDateField.Equals(value) <> true) Then
                    Me.LastOrderDateField = value
                    Me.RaisePropertyChanged("LastOrderDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumOrders() As Integer
            Get
                Return Me.NumOrdersField
            End Get
            Set
                If (Me.NumOrdersField.Equals(value) <> true) Then
                    Me.NumOrdersField = value
                    Me.RaisePropertyChanged("NumOrders")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Orders() As ActionServiceReference.Order()
            Get
                Return Me.OrdersField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrdersField, value) <> true) Then
                    Me.OrdersField = value
                    Me.RaisePropertyChanged("Orders")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Version() As String
            Get
                Return Me.VersionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VersionField, value) <> true) Then
                    Me.VersionField = value
                    Me.RaisePropertyChanged("Version")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Criteria", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.OrderCriteria)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.ProductCriteria)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.CustomerCriteria))>  _
    Partial Public Class Criteria
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SortExpressionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SortExpression() As String
            Get
                Return Me.SortExpressionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SortExpressionField, value) <> true) Then
                    Me.SortExpressionField = value
                    Me.RaisePropertyChanged("SortExpression")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OrderCriteria", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OrderCriteria
        Inherits ActionServiceReference.Criteria
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderIdField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomerId() As Integer
            Get
                Return Me.CustomerIdField
            End Get
            Set
                If (Me.CustomerIdField.Equals(value) <> true) Then
                    Me.CustomerIdField = value
                    Me.RaisePropertyChanged("CustomerId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderId() As Integer
            Get
                Return Me.OrderIdField
            End Get
            Set
                If (Me.OrderIdField.Equals(value) <> true) Then
                    Me.OrderIdField = value
                    Me.RaisePropertyChanged("OrderId")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ProductCriteria", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ProductCriteria
        Inherits ActionServiceReference.Criteria
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CategoryIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PriceFromField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PriceThruField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductNameField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CategoryId() As Integer
            Get
                Return Me.CategoryIdField
            End Get
            Set
                If (Me.CategoryIdField.Equals(value) <> true) Then
                    Me.CategoryIdField = value
                    Me.RaisePropertyChanged("CategoryId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PriceFrom() As Double
            Get
                Return Me.PriceFromField
            End Get
            Set
                If (Me.PriceFromField.Equals(value) <> true) Then
                    Me.PriceFromField = value
                    Me.RaisePropertyChanged("PriceFrom")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PriceThru() As Double
            Get
                Return Me.PriceThruField
            End Get
            Set
                If (Me.PriceThruField.Equals(value) <> true) Then
                    Me.PriceThruField = value
                    Me.RaisePropertyChanged("PriceThru")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProductId() As Integer
            Get
                Return Me.ProductIdField
            End Get
            Set
                If (Me.ProductIdField.Equals(value) <> true) Then
                    Me.ProductIdField = value
                    Me.RaisePropertyChanged("ProductId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProductName() As String
            Get
                Return Me.ProductNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductNameField, value) <> true) Then
                    Me.ProductNameField = value
                    Me.RaisePropertyChanged("ProductName")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Order", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Order
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerField As ActionServiceReference.Customer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FreightField As Single
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderDetailsField() As ActionServiceReference.OrderDetail
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RequiredDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VersionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Customer() As ActionServiceReference.Customer
            Get
                Return Me.CustomerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomerField, value) <> true) Then
                    Me.CustomerField = value
                    Me.RaisePropertyChanged("Customer")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Freight() As Single
            Get
                Return Me.FreightField
            End Get
            Set
                If (Me.FreightField.Equals(value) <> true) Then
                    Me.FreightField = value
                    Me.RaisePropertyChanged("Freight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderDate() As Date
            Get
                Return Me.OrderDateField
            End Get
            Set
                If (Me.OrderDateField.Equals(value) <> true) Then
                    Me.OrderDateField = value
                    Me.RaisePropertyChanged("OrderDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderDetails() As ActionServiceReference.OrderDetail()
            Get
                Return Me.OrderDetailsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrderDetailsField, value) <> true) Then
                    Me.OrderDetailsField = value
                    Me.RaisePropertyChanged("OrderDetails")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderId() As Integer
            Get
                Return Me.OrderIdField
            End Get
            Set
                If (Me.OrderIdField.Equals(value) <> true) Then
                    Me.OrderIdField = value
                    Me.RaisePropertyChanged("OrderId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RequiredDate() As Date
            Get
                Return Me.RequiredDateField
            End Get
            Set
                If (Me.RequiredDateField.Equals(value) <> true) Then
                    Me.RequiredDateField = value
                    Me.RaisePropertyChanged("RequiredDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Version() As String
            Get
                Return Me.VersionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VersionField, value) <> true) Then
                    Me.VersionField = value
                    Me.RaisePropertyChanged("Version")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OrderDetail", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OrderDetail
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DiscountField As Single
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QuantityField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UnitPriceField As Single
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VersionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Discount() As Single
            Get
                Return Me.DiscountField
            End Get
            Set
                If (Me.DiscountField.Equals(value) <> true) Then
                    Me.DiscountField = value
                    Me.RaisePropertyChanged("Discount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProductName() As String
            Get
                Return Me.ProductNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductNameField, value) <> true) Then
                    Me.ProductNameField = value
                    Me.RaisePropertyChanged("ProductName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Quantity() As Integer
            Get
                Return Me.QuantityField
            End Get
            Set
                If (Me.QuantityField.Equals(value) <> true) Then
                    Me.QuantityField = value
                    Me.RaisePropertyChanged("Quantity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UnitPrice() As Single
            Get
                Return Me.UnitPriceField
            End Get
            Set
                If (Me.UnitPriceField.Equals(value) <> true) Then
                    Me.UnitPriceField = value
                    Me.RaisePropertyChanged("UnitPrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Version() As String
            Get
                Return Me.VersionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VersionField, value) <> true) Then
                    Me.VersionField = value
                    Me.RaisePropertyChanged("Version")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ShoppingCartItem", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ShoppingCartItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QuantityField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UnitPriceField As Double
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Quantity() As Integer
            Get
                Return Me.QuantityField
            End Get
            Set
                If (Me.QuantityField.Equals(value) <> true) Then
                    Me.QuantityField = value
                    Me.RaisePropertyChanged("Quantity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UnitPrice() As Double
            Get
                Return Me.UnitPriceField
            End Get
            Set
                If (Me.UnitPriceField.Equals(value) <> true) Then
                    Me.UnitPriceField = value
                    Me.RaisePropertyChanged("UnitPrice")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponseBase", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.LoginResponse)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.LogoutResponse)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.CustomerResponse)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.OrderResponse)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.ProductResponse)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.CartResponse)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ActionServiceReference.TokenResponse))>  _
    Partial Public Class ResponseBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AcknowledgeField As ActionServiceReference.AcknowledgeType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BuildField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CorrelationIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReservationExpiresField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReservationIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RowsAffectedField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VersionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Acknowledge() As ActionServiceReference.AcknowledgeType
            Get
                Return Me.AcknowledgeField
            End Get
            Set
                If (Me.AcknowledgeField.Equals(value) <> true) Then
                    Me.AcknowledgeField = value
                    Me.RaisePropertyChanged("Acknowledge")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Build() As String
            Get
                Return Me.BuildField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BuildField, value) <> true) Then
                    Me.BuildField = value
                    Me.RaisePropertyChanged("Build")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CorrelationId() As String
            Get
                Return Me.CorrelationIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CorrelationIdField, value) <> true) Then
                    Me.CorrelationIdField = value
                    Me.RaisePropertyChanged("CorrelationId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReservationExpires() As Date
            Get
                Return Me.ReservationExpiresField
            End Get
            Set
                If (Me.ReservationExpiresField.Equals(value) <> true) Then
                    Me.ReservationExpiresField = value
                    Me.RaisePropertyChanged("ReservationExpires")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReservationId() As String
            Get
                Return Me.ReservationIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReservationIdField, value) <> true) Then
                    Me.ReservationIdField = value
                    Me.RaisePropertyChanged("ReservationId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RowsAffected() As Integer
            Get
                Return Me.RowsAffectedField
            End Get
            Set
                If (Me.RowsAffectedField.Equals(value) <> true) Then
                    Me.RowsAffectedField = value
                    Me.RaisePropertyChanged("RowsAffected")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Version() As String
            Get
                Return Me.VersionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VersionField, value) <> true) Then
                    Me.VersionField = value
                    Me.RaisePropertyChanged("Version")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LoginResponse", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LoginResponse
        Inherits ActionServiceReference.ResponseBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SessionIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UriField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SessionId() As String
            Get
                Return Me.SessionIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SessionIdField, value) <> true) Then
                    Me.SessionIdField = value
                    Me.RaisePropertyChanged("SessionId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Uri() As String
            Get
                Return Me.UriField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UriField, value) <> true) Then
                    Me.UriField = value
                    Me.RaisePropertyChanged("Uri")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LogoutResponse", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LogoutResponse
        Inherits ActionServiceReference.ResponseBase
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CustomerResponse", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CustomerResponse
        Inherits ActionServiceReference.ResponseBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerField As ActionServiceReference.Customer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomersField() As ActionServiceReference.Customer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Customer() As ActionServiceReference.Customer
            Get
                Return Me.CustomerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomerField, value) <> true) Then
                    Me.CustomerField = value
                    Me.RaisePropertyChanged("Customer")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Customers() As ActionServiceReference.Customer()
            Get
                Return Me.CustomersField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomersField, value) <> true) Then
                    Me.CustomersField = value
                    Me.RaisePropertyChanged("Customers")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OrderResponse", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OrderResponse
        Inherits ActionServiceReference.ResponseBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderField As ActionServiceReference.Order
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrdersField() As ActionServiceReference.Order
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Order() As ActionServiceReference.Order
            Get
                Return Me.OrderField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrderField, value) <> true) Then
                    Me.OrderField = value
                    Me.RaisePropertyChanged("Order")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Orders() As ActionServiceReference.Order()
            Get
                Return Me.OrdersField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrdersField, value) <> true) Then
                    Me.OrdersField = value
                    Me.RaisePropertyChanged("Orders")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ProductResponse", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ProductResponse
        Inherits ActionServiceReference.ResponseBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CategoriesField() As ActionServiceReference.Category
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductField As ActionServiceReference.Product
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductsField() As ActionServiceReference.Product
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Categories() As ActionServiceReference.Category()
            Get
                Return Me.CategoriesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CategoriesField, value) <> true) Then
                    Me.CategoriesField = value
                    Me.RaisePropertyChanged("Categories")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Product() As ActionServiceReference.Product
            Get
                Return Me.ProductField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductField, value) <> true) Then
                    Me.ProductField = value
                    Me.RaisePropertyChanged("Product")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Products() As ActionServiceReference.Product()
            Get
                Return Me.ProductsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductsField, value) <> true) Then
                    Me.ProductsField = value
                    Me.RaisePropertyChanged("Products")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CartResponse", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CartResponse
        Inherits ActionServiceReference.ResponseBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CartField As ActionServiceReference.ShoppingCart
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cart() As ActionServiceReference.ShoppingCart
            Get
                Return Me.CartField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CartField, value) <> true) Then
                    Me.CartField = value
                    Me.RaisePropertyChanged("Cart")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TokenResponse", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TokenResponse
        Inherits ActionServiceReference.ResponseBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AccessTokenField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AccessToken() As String
            Get
                Return Me.AccessTokenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccessTokenField, value) <> true) Then
                    Me.AccessTokenField = value
                    Me.RaisePropertyChanged("AccessToken")
                End If
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AcknowledgeType", [Namespace]:="http://www.yourcompany.com/types/")>  _
    Public Enum AcknowledgeType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Failure = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Success = 1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Product", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Product
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CategoryField As ActionServiceReference.Category
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UnitPriceField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UnitsInStockField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VersionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WeightField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Category() As ActionServiceReference.Category
            Get
                Return Me.CategoryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CategoryField, value) <> true) Then
                    Me.CategoryField = value
                    Me.RaisePropertyChanged("Category")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProductId() As Integer
            Get
                Return Me.ProductIdField
            End Get
            Set
                If (Me.ProductIdField.Equals(value) <> true) Then
                    Me.ProductIdField = value
                    Me.RaisePropertyChanged("ProductId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProductName() As String
            Get
                Return Me.ProductNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductNameField, value) <> true) Then
                    Me.ProductNameField = value
                    Me.RaisePropertyChanged("ProductName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UnitPrice() As Double
            Get
                Return Me.UnitPriceField
            End Get
            Set
                If (Me.UnitPriceField.Equals(value) <> true) Then
                    Me.UnitPriceField = value
                    Me.RaisePropertyChanged("UnitPrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UnitsInStock() As Integer
            Get
                Return Me.UnitsInStockField
            End Get
            Set
                If (Me.UnitsInStockField.Equals(value) <> true) Then
                    Me.UnitsInStockField = value
                    Me.RaisePropertyChanged("UnitsInStock")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Version() As String
            Get
                Return Me.VersionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VersionField, value) <> true) Then
                    Me.VersionField = value
                    Me.RaisePropertyChanged("Version")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Weight() As String
            Get
                Return Me.WeightField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WeightField, value) <> true) Then
                    Me.WeightField = value
                    Me.RaisePropertyChanged("Weight")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Category", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Category
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CategoryIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VersionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CategoryId() As Integer
            Get
                Return Me.CategoryIdField
            End Get
            Set
                If (Me.CategoryIdField.Equals(value) <> true) Then
                    Me.CategoryIdField = value
                    Me.RaisePropertyChanged("CategoryId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Version() As String
            Get
                Return Me.VersionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VersionField, value) <> true) Then
                    Me.VersionField = value
                    Me.RaisePropertyChanged("Version")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ShoppingCart", [Namespace]:="http://www.yourcompany.com/types/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ShoppingCart
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CartItemsField() As ActionServiceReference.ShoppingCartItem
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ShippingField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ShippingMethodField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubTotalField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TotalField As Double
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CartItems() As ActionServiceReference.ShoppingCartItem()
            Get
                Return Me.CartItemsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CartItemsField, value) <> true) Then
                    Me.CartItemsField = value
                    Me.RaisePropertyChanged("CartItems")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Shipping() As Double
            Get
                Return Me.ShippingField
            End Get
            Set
                If (Me.ShippingField.Equals(value) <> true) Then
                    Me.ShippingField = value
                    Me.RaisePropertyChanged("Shipping")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ShippingMethod() As String
            Get
                Return Me.ShippingMethodField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ShippingMethodField, value) <> true) Then
                    Me.ShippingMethodField = value
                    Me.RaisePropertyChanged("ShippingMethod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubTotal() As Double
            Get
                Return Me.SubTotalField
            End Get
            Set
                If (Me.SubTotalField.Equals(value) <> true) Then
                    Me.SubTotalField = value
                    Me.RaisePropertyChanged("SubTotal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Total() As Double
            Get
                Return Me.TotalField
            End Get
            Set
                If (Me.TotalField.Equals(value) <> true) Then
                    Me.TotalField = value
                    Me.RaisePropertyChanged("Total")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ActionServiceReference.IActionService", SessionMode:=System.ServiceModel.SessionMode.Required)>  _
    Public Interface IActionService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActionService/GetToken", ReplyAction:="http://tempuri.org/IActionService/GetTokenResponse")>  _
        Function GetToken(ByVal request As ActionServiceReference.TokenRequest) As ActionServiceReference.TokenResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActionService/Login", ReplyAction:="http://tempuri.org/IActionService/LoginResponse")>  _
        Function Login(ByVal request As ActionServiceReference.LoginRequest) As ActionServiceReference.LoginResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActionService/Logout", ReplyAction:="http://tempuri.org/IActionService/LogoutResponse")>  _
        Function Logout(ByVal request As ActionServiceReference.LogoutRequest) As ActionServiceReference.LogoutResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActionService/GetCustomers", ReplyAction:="http://tempuri.org/IActionService/GetCustomersResponse")>  _
        Function GetCustomers(ByVal request As ActionServiceReference.CustomerRequest) As ActionServiceReference.CustomerResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActionService/SetCustomers", ReplyAction:="http://tempuri.org/IActionService/SetCustomersResponse")>  _
        Function SetCustomers(ByVal request As ActionServiceReference.CustomerRequest) As ActionServiceReference.CustomerResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActionService/GetOrders", ReplyAction:="http://tempuri.org/IActionService/GetOrdersResponse")>  _
        Function GetOrders(ByVal request As ActionServiceReference.OrderRequest) As ActionServiceReference.OrderResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActionService/SetOrders", ReplyAction:="http://tempuri.org/IActionService/SetOrdersResponse")>  _
        Function SetOrders(ByVal request As ActionServiceReference.OrderRequest) As ActionServiceReference.OrderResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActionService/GetProducts", ReplyAction:="http://tempuri.org/IActionService/GetProductsResponse")>  _
        Function GetProducts(ByVal request As ActionServiceReference.ProductRequest) As ActionServiceReference.ProductResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActionService/SetProducts", ReplyAction:="http://tempuri.org/IActionService/SetProductsResponse")>  _
        Function SetProducts(ByVal request As ActionServiceReference.ProductRequest) As ActionServiceReference.ProductResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActionService/GetCart", ReplyAction:="http://tempuri.org/IActionService/GetCartResponse")>  _
        Function GetCart(ByVal request As ActionServiceReference.CartRequest) As ActionServiceReference.CartResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IActionService/SetCart", ReplyAction:="http://tempuri.org/IActionService/SetCartResponse")>  _
        Function SetCart(ByVal request As ActionServiceReference.CartRequest) As ActionServiceReference.CartResponse
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IActionServiceChannel
        Inherits ActionServiceReference.IActionService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ActionServiceClient
        Inherits System.ServiceModel.ClientBase(Of ActionServiceReference.IActionService)
        Implements ActionServiceReference.IActionService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetToken(ByVal request As ActionServiceReference.TokenRequest) As ActionServiceReference.TokenResponse Implements ActionServiceReference.IActionService.GetToken
            Return MyBase.Channel.GetToken(request)
        End Function
        
        Public Function Login(ByVal request As ActionServiceReference.LoginRequest) As ActionServiceReference.LoginResponse Implements ActionServiceReference.IActionService.Login
            Return MyBase.Channel.Login(request)
        End Function
        
        Public Function Logout(ByVal request As ActionServiceReference.LogoutRequest) As ActionServiceReference.LogoutResponse Implements ActionServiceReference.IActionService.Logout
            Return MyBase.Channel.Logout(request)
        End Function
        
        Public Function GetCustomers(ByVal request As ActionServiceReference.CustomerRequest) As ActionServiceReference.CustomerResponse Implements ActionServiceReference.IActionService.GetCustomers
            Return MyBase.Channel.GetCustomers(request)
        End Function
        
        Public Function SetCustomers(ByVal request As ActionServiceReference.CustomerRequest) As ActionServiceReference.CustomerResponse Implements ActionServiceReference.IActionService.SetCustomers
            Return MyBase.Channel.SetCustomers(request)
        End Function
        
        Public Function GetOrders(ByVal request As ActionServiceReference.OrderRequest) As ActionServiceReference.OrderResponse Implements ActionServiceReference.IActionService.GetOrders
            Return MyBase.Channel.GetOrders(request)
        End Function
        
        Public Function SetOrders(ByVal request As ActionServiceReference.OrderRequest) As ActionServiceReference.OrderResponse Implements ActionServiceReference.IActionService.SetOrders
            Return MyBase.Channel.SetOrders(request)
        End Function
        
        Public Function GetProducts(ByVal request As ActionServiceReference.ProductRequest) As ActionServiceReference.ProductResponse Implements ActionServiceReference.IActionService.GetProducts
            Return MyBase.Channel.GetProducts(request)
        End Function
        
        Public Function SetProducts(ByVal request As ActionServiceReference.ProductRequest) As ActionServiceReference.ProductResponse Implements ActionServiceReference.IActionService.SetProducts
            Return MyBase.Channel.SetProducts(request)
        End Function
        
        Public Function GetCart(ByVal request As ActionServiceReference.CartRequest) As ActionServiceReference.CartResponse Implements ActionServiceReference.IActionService.GetCart
            Return MyBase.Channel.GetCart(request)
        End Function
        
        Public Function SetCart(ByVal request As ActionServiceReference.CartRequest) As ActionServiceReference.CartResponse Implements ActionServiceReference.IActionService.SetCart
            Return MyBase.Channel.SetCart(request)
        End Function
    End Class
End Namespace
