'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace ASPNETWebApplication.WebShop


	Partial Public Class Cart

		''' <summary>
		''' UpdatePanel1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected UpdatePanel1 As Global.System.Web.UI.UpdatePanel

		''' <summary>
		''' HyperLinkContinueShopping control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected HyperLinkContinueShopping As Global.System.Web.UI.WebControls.HyperLink

		''' <summary>
		''' HyperLinkCheckout control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected HyperLinkCheckout As Global.System.Web.UI.WebControls.HyperLink

		''' <summary>
		''' GridViewCart control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected GridViewCart As Global.System.Web.UI.WebControls.GridView

		''' <summary>
		''' LinkbuttonRecalculate control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected LinkbuttonRecalculate As Global.System.Web.UI.WebControls.LinkButton

		''' <summary>
		''' ImageSpacer1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ImageSpacer1 As Global.System.Web.UI.WebControls.Image

		''' <summary>
		''' DropDownListShipping control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected DropDownListShipping As Global.System.Web.UI.WebControls.DropDownList

		''' <summary>
		''' ImageSpacer2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ImageSpacer2 As Global.System.Web.UI.WebControls.Image

		''' <summary>
		''' ImageSpacer3 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ImageSpacer3 As Global.System.Web.UI.WebControls.Image

		''' <summary>
		''' HyperLinkCheckoutBottom control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected HyperLinkCheckoutBottom As Global.System.Web.UI.WebControls.HyperLink

		''' <summary>
		''' Master property.
		''' </summary>
		''' <remarks>
		''' Auto-generated property.
		''' </remarks>
		Public Shadows ReadOnly Property Master() As ASPNETWebApplication.SiteMasterPage
			Get
				Return (CType(MyBase.Master, ASPNETWebApplication.SiteMasterPage))
			End Get
		End Property
	End Class
End Namespace
