'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ASPNETWebApplication.WebShop

    Partial Public Class Product

        '''<summary>
        '''HyperLinkBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HyperLinkBack As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''ImageProduct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageProduct As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''DetailViewProduct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DetailViewProduct As Global.System.Web.UI.WebControls.DetailsView

        '''<summary>
        '''ObjectDataSourceProduct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjectDataSourceProduct As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''TextBoxQuantity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxQuantity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ButtonAddToCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonAddToCart As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ValidationSummaryQuantity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummaryQuantity As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''RequiredFieldValidatorQuantity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidatorQuantity As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''RangeValidatorQuantity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RangeValidatorQuantity As Global.System.Web.UI.WebControls.RangeValidator

        '''<summary>
        '''CompareValidatorQuantity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CompareValidatorQuantity As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As ASPNETWebApplication.SiteMasterPage
            Get
                Return CType(MyBase.Master, ASPNETWebApplication.SiteMasterPage)
            End Get
        End Property
    End Class
End Namespace
