'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace DoFactory.HeadFirst.Proxy.GumballState.Client.GumballProxy


	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), System.ServiceModel.ServiceContractAttribute(Namespace:="http://www.mycompany.com/headfirst/2008/07", ConfigurationName:="GumballProxy.GumballMachine", SessionMode:=System.ServiceModel.SessionMode.Required)> _
	Public Interface GumballMachine

		<System.ServiceModel.OperationContractAttribute(Action:="http://www.mycompany.com/headfirst/2008/07/GumballMachine/StartWithQuarters", ReplyAction:="http://www.mycompany.com/headfirst/2008/07/GumballMachine/StartWithQuartersRespon" & "se")> _
		Sub StartWithQuarters(ByVal count As Integer)

		<System.ServiceModel.OperationContractAttribute(Action:="http://www.mycompany.com/headfirst/2008/07/GumballMachine/InsertQuarter", ReplyAction:="http://www.mycompany.com/headfirst/2008/07/GumballMachine/InsertQuarterResponse")> _
		Sub InsertQuarter()

		<System.ServiceModel.OperationContractAttribute(Action:="http://www.mycompany.com/headfirst/2008/07/GumballMachine/TurnCrank", ReplyAction:="http://www.mycompany.com/headfirst/2008/07/GumballMachine/TurnCrankResponse")> _
		Sub TurnCrank()

		<System.ServiceModel.OperationContractAttribute(Action:="http://www.mycompany.com/headfirst/2008/07/GumballMachine/EjectQuarter", ReplyAction:="http://www.mycompany.com/headfirst/2008/07/GumballMachine/EjectQuarterResponse")> _
		Sub EjectQuarter()

		<System.ServiceModel.OperationContractAttribute(Action:="http://www.mycompany.com/headfirst/2008/07/GumballMachine/GetReport", ReplyAction:="http://www.mycompany.com/headfirst/2008/07/GumballMachine/GetReportResponse")> _
		Function GetReport() As String
	End Interface

	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
	Public Interface GumballMachineChannel
	Inherits DoFactory.HeadFirst.Proxy.GumballState.Client.GumballProxy.GumballMachine, System.ServiceModel.IClientChannel
	End Interface

	<System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
	Partial Public Class GumballMachineClient
		Inherits System.ServiceModel.ClientBase(Of DoFactory.HeadFirst.Proxy.GumballState.Client.GumballProxy.GumballMachine)
		Implements DoFactory.HeadFirst.Proxy.GumballState.Client.GumballProxy.GumballMachine

		Public Sub New()
		End Sub

		Public Sub New(ByVal endpointConfigurationName As String)
			MyBase.New(endpointConfigurationName)
		End Sub

		Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
			MyBase.New(endpointConfigurationName, remoteAddress)
		End Sub

		Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
			MyBase.New(endpointConfigurationName, remoteAddress)
		End Sub

		Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
			MyBase.New(binding, remoteAddress)
		End Sub

		Public Sub StartWithQuarters(ByVal count As Integer) Implements DoFactory.HeadFirst.Proxy.GumballState.Client.GumballProxy.GumballMachine.StartWithQuarters
			MyBase.Channel.StartWithQuarters(count)
		End Sub

		Public Sub InsertQuarter() Implements DoFactory.HeadFirst.Proxy.GumballState.Client.GumballProxy.GumballMachine.InsertQuarter
			MyBase.Channel.InsertQuarter()
		End Sub

		Public Sub TurnCrank() Implements DoFactory.HeadFirst.Proxy.GumballState.Client.GumballProxy.GumballMachine.TurnCrank
			MyBase.Channel.TurnCrank()
		End Sub

		Public Sub EjectQuarter() Implements DoFactory.HeadFirst.Proxy.GumballState.Client.GumballProxy.GumballMachine.EjectQuarter
			MyBase.Channel.EjectQuarter()
		End Sub

		Public Function GetReport() As String Implements DoFactory.HeadFirst.Proxy.GumballState.Client.GumballProxy.GumballMachine.GetReport
			Return MyBase.Channel.GetReport()
		End Function
	End Class
End Namespace
